# Generated by Django 5.2.7 on 2026-04-17 10:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload product image to Cloudinary', max_length=255, null=True, verbose_name='product_image'),
        ),
    ]
